### ISSUE TITLE
Audio playback errors until first user interaction

### ISSUE THREAD

**Issue by quinnouyang** [staylor7/rare#8]
- See https://goo.gl/xX8pDD
- Easiest (and probably intended) solution is to require user to click something/somewhere (reasonable) to start
- Autoplay on _mute_ is okay (we should include a volume control and toggle in general)

Thoughts?

**Comment by SallyXue-0114** [comment]
I agree with this solution: require user to click something/somewhere (reasonable) to start. If we're dealing with multiple functions in the future, we can create individual buttons (or navbars?) for each.

Another thought is: perhaps we could consider enabling each audio playback through a click action rather than hovering? Not sure how hard is it to implement clicking though, and 'click' might conflict with other functions (e.g: zoomable).

**Comment by staylor7** [comment]
Yes, several years ago the Web Audio API changed so a user has to click something - anything - to start audio. This is so a user doesn’t get blasted when they navigate to a webpage.

In other projects I’ve made it so you can click anywhere on the page. Thanks for catching this!

**Comment by quinnouyang** [comment]
I do like being able to hover wherever I want and getting a bunch of playback (until it starts clipping...that's a separate issue) and clicking will be difficult on the small arc sizes we have at the moment. Maybe sundial will be more click friendly?

Alternatively, we can try a "Click here to start" entry-point to click (some immersive audio-visual sites do this very well) if we have a creative way to execute that.

**Comment by quinnouyang** [comment]
Closing since playback is now via click vs. hover.

Would we like this to always be the case? Can be first click, then always hover (or only enable hover for diseases, though that's inconsistent UI). @staylor7 @SallyXue-0114

**Comment by staylor7** [comment]
Thanks you two! Would it be worth it to set up a zoom later today? I could also meet in person if that’s better. 

I think Web Audio doesn’t start without a mouse click somewhere - that’s because having sound right as the page loads could be really distracting. 

My colleague Aditi has finished all the tooltip short descriptions for all the diseases, as well as adding an extra field with a hyperlink for more info. Should I update the spreadsheet on GitHub to include these?

Thanks!

Steve
_________________________________
Stephen Taylor
Professor of Composition-Theory
School of Music, University of Illinois at Urbana-Champaign
co-director, Illinois Modern Ensemble
www.stephenandrewtaylor.net
217 333-3712 office

**Comment by quinnouyang** [comment]
I'm free to call for a bit in the late afternoon, say around 5 PM. Let's keep to clicks-only then.

Sure, update the CSV!

**Comment by quinnouyang** [comment]
@staylor7 I'm free to call for a bit in the late afternoon, say around 5 PM. Let's keep to clicks-only then.

Sure, update the CSV!

**Comment by staylor7** [comment]
5 pm works for me, thanks!

**Comment by SallyXue-0114** [comment]
5pm works for me as well!

- sally

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Stephen Taylor ***@***.***>
发送时间: Tuesday, March 12, 2024 12:16:05 PM
收件人: staylor7/rare-diseases ***@***.***>
抄送: Xue, Sally ***@***.***>; Mention ***@***.***>
主题: Re: [staylor7/rare-diseases] Audio playback errors until first user interaction (Issue #8)


5 pm works for me, thanks!

**Comment by staylor7** [comment]
Great! We can use this zoom link-

Join Zoom Meeting
https://illinois.zoom.us/j/6479025315?pwd=RS9Edk1TRzlWTi9uS1Mrc0lZbHR0UT09

Meeting ID: 647 902 5315
Password: 213160
