### ISSUE TITLE
Migrate to the fun zoomable sunburst diagram

### ISSUE THREAD

**Issue by quinnouyang** [staylor7/rare#9]
- Example: https://observablehq.com/@d3/zoomable-sunburst
- Requires turning `.csv` to a hierarchical `.json`. See https://d3js.org/d3-hierarchy/stratify
- @staylor7 's attempt: https://observablehq.com/d/6a5d607535b9bd1b

**Comment by SallyXue-0114** [comment]
What should the hierarchy of our CSV file be? For example, our CSV header is as follows:
index, Disease, Disease_break, Category, Chakra, Nphenotype, Ngenes, Elite, Inheritance, Nvariants, Phenotype, Gene, Promoter, Malacards.
Should we place 'Disease' in layer 1 (top layer) and all other elements in layer 2?

**Comment by staylor7** [comment]
We can get rid of Disease_break - that was me trying to make line breaks in the disease names, just a hack that didn’t work.

I think that “Category” and “Chakra” should be layer 1, and everything else layer 2.

Aditi, the doctor I’m working with, assigned Indian chakras to each of the 12 disease categories - the chakras are what determine the musical scale for that category. So they are equivalent in the csv.

Thanks Sally!

**Comment by quinnouyang** [comment]
I made some progress on stratifying the data (I specified a more detailed hierarchy than the two layers that @staylor7 proposed.), though I could not get the sunburst to render yet. See https://github.com/staylor7/rare-diseases/blob/83aac099fee8e5cdb08a2a3b3ba5e7342018407a/src/sunburst.ts#L16C1-L26C2 

(Accidently committed these to `main`, whoops.)

**Comment by SallyXue-0114** [comment]
thanks quinn! Will take a look today!

**Comment by staylor7** [comment]
I will try this too but I keep forgetting how to do the whole build thing in Terminal. Sorry I’m so behind - oy!

Steve
_________________________________
Stephen Taylor
Professor of Music
University of Illinois at Urbana-Champaign
Co-director, Illinois Modern Ensemble
www.stephenandrewtaylor.net
217 333-3712 office

**Comment by SallyXue-0114** [comment]
New updates from Sally:

1. I managed to fix all the 'Problems' (the red wiggly lines) in Quinn's version of the code, but it's still not displaying anything. The issue might be related to the connection with main.ts? I've pushed my changes to the main branch.

2. In the 'sunburst-js' branch: Earlier, I converted our data (CSV file) into a two-layer (the one @staylor7 proposed)  stratified JSON file (hierarchy.json). Now, when I run script.js (I do this by using the 'Go Live' button in VSCode), it displays some kind of sunburst as shown in the following screenshot (this is just half of it; it's too large to capture entirely).
<img width="1406" alt="sunburst" src="https://github.com/staylor7/rare-diseases/assets/92959551/e0ce6fb9-ee80-4c60-8b65-cf70460992ac">

However, it's a bit messy at the moment (and sometimes freezes) because there's so much information in our CSV file.
